### ISSUE TITLE
ModelBuilder Class

### ISSUE THREAD

**Issue by thodson-usgs** [thodson-usgs/ratingcurve#39]
Replace scipy interface with experimental model builder class
https://www.pymc.io/projects/examples/en/latest/howto/model_builder.html

Also note how this example configures sampler parameters by`@property`, which seems cleaner than the current approach.

**Comment by kjdoore** [comment]
This looks like the way to go if it works as advertised.

**Comment by kjdoore** [comment]
Implemented with #46.
