### ISSUE TITLE
Error in powerrating.table(trace)

### ISSUE THREAD

**Issue by marciocemaden** [thodson-usgs/ratingcurve#51]
Model run withou error, like below:

powerrating = PowerLawRating(q=df['Discharge'], h=df['Stages'], q_sigma = df['q_sigma'],segments=2, prior={'distribution':'uniform'})

trace = powerrating.fit(q=df['Discharge'],h=df['Stages'])
 |███---------------| 20.27% [40546/200000 01:27<05:43 Average Loss = 10,698]05]Convergence achieved at 40600
Interrupted at 40,599 [20%]: Average Loss = 9.2743e+05
Sampling: [a, b, hs_, model_q, sigma]
█Sampling: [model_q]
 |████████████████████| 100.00% [10000/10000 00:07<00:00]

But, when try to get table
table = powerrating.table(trace)
 
Get this error:

File ~\AppData\Local\anaconda3\lib\site-packages\pymc\pytensorf.py:122 in convert_observed_data
    # already a ndarray, but not masked

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by thodson-usgs** [comment]
Hi @marciocemaden,
Looks like you're running on Windows is that correct?
We try to test on Windows, but we typically work in Linux (WSL), so running in Windows tends to be buggier. 

What data are you using?
I'm wondering whether this error occurs when you run the tutorials, or is it something about your dataset?

**Comment by marciocemaden** [comment]
Hi Thodson,

On Mac OS there are bugs?
I'm testing with real data get from gauges.
Thank you

Em seg., 6 de nov. de 2023 17:43, Timothy Hodson ***@***.***>
escreveu:

**Comment by kjdoore** [comment]
Hi @marciocemaden,

After looking at this, I noticed that this is actually a documentation issue on our end. We made a major update to the package a few weeks ago and completely forgot to make sure that the GitHub Action correctly updated the docs. I will get this fixed such that the docs are correctly updated. As for your issue, you can get the table output to work by excluding the `trace` variable in the input. In other words
```
table = powerrating.table()
```
should do the trick. Sorry about that.

**Comment by kjdoore** [comment]
Hi @marciocemaden,

We have finished fixing our doc issue. All docs are now up to date and reflect the current syntax of the package. Feel free to check them out and let us know if you have any further issues. Sorry about any confusion that may have caused.

**Comment by marciocemaden** [comment]
Thank you for your email.
Good to hear from you about this update.
I'm having a little problem using the routine. The plot below shows what's
happening.

powerrating = PowerLawRating(segments=1, prior={'distribution':'uniform'})
trace = powerrating.fit(q=x, h=y)
powerrating.plot()
[image: image.png]
The behavior of the data is more similar to a power function growing with a
slope to the right,
while the adjustment performed by the routine is growing with a slope to
the left.
Could you tell me why the routine is diverging from the data?
Thanks a lot
Marcio.
[image: cemaden_logo] <http://www.cemaden.gov.br>   Marcio A E Moraes
Pesquisador Adjunto II
Estrada Doutor Altino Bondesan, 500 - Distrito de Eugênio de Melo, São José
dos Campos/SP
CEP:12.247-016
Telefone : +55 (12) 12 3205-0146
www.cemaden.gov.br

**Comment by thodson-usgs** [comment]
The image is not appearing. If you paste it in normally, GitHub will magically create a markdown link.
Feel free to email me if it does not.
