### ISSUE TITLE
Summing variances not STD in Gaussian pdf

### ISSUE THREAD

**Issue by RafaelVias** [thodson-usgs/ratingcurve#61]
When defining the likelihood function in ratings.py (currently in line 129), shouldn't the standard deviation of the Gaussian pdf be the square root of the sum of the variances, not the sum of the standard deviations?
That is, shouldn´t `sigma=sigma + q_sigma` be `sigma=np.sqrt(sigma**2 + q_sigma**2)`.

See; https://en.wikipedia.org/wiki/Sum_of_normally_distributed_random_variables.

**Comment by thodson-usgs** [comment]
Good catch! Would you like to open the PR or shall I?

**Comment by thodson-usgs** [comment]
@RafaelVias, also want to alert you to #62. We should have time to tackle it, but we would welcome any PRs on generalized power law.

**Comment by kjdoore** [comment]
Yeah, after checking, this will need to be updated for all of the rating models. I thought I fixed this at some point but must not have. Thanks for pointing it out!

**Comment by RafaelVias** [comment]
> Good catch! Would you like to open the PR or shall I?

NP! Just now created a PR.

**Comment by RafaelVias** [comment]
> @RafaelVias, also want to alert you to #62. We should have time to tackle it, but we would welcome any PRs on generalized power law.

Fantastic! We can certainly help implement the generalized power-law model in `ratingcurve`.

**Comment by kjdoore** [comment]
Fixed with #63
